
-- Counts de las tablas

SELECT COUNT(DISTINCT Codigo) FROM Venta;
SELECT COUNT(DISTINCT Codigo) FROM Compra;
SELECT COUNT(DISTINCT Codigo) FROM Cliente;
SELECT COUNT(DISTINCT Codigo) FROM Vendedor;
SELECT COUNT(DISTINCT Codigo) FROM Producto;
SELECT COUNT(DISTINCT Codigo) FROM Tiempo;
SELECT COUNT(DISTINCT Codigo) FROM Region;
SELECT COUNT(DISTINCT Codigo) FROM Sucursal;
SELECT COUNT(DISTINCT Codigo) FROM Proveedor;